# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.15.4

# Mod Properties
mod_version=0.1.0-alpha.1
maven_group=com.jelly.farmhelper
archives_base_name=farmhelper-fabric
mod_id=farmhelperfabric
mod_name=FarmHelper Fabric

# Dependencies
fabric_version=0.141.3+1.21.11

yarn_mappings=1.21.11+build.4
